### ISSUE TITLE
Platform specific files seem to be missing

### ISSUE THREAD

**Issue by ruipacheco** [aseprite/libuv-cmake#2]
I've compared the source for libuv and the files you list on cmake and platform specific files for *nix OS' seem to be missing. Files like freebsd.c, openbsd.c, linux* and darwin*. Is this on purpose?

**Comment by dacap** [comment]
Hi @ruipacheco. This project is a little outdated. I've used it just for some testing, but it was never used in production. If something is missing from the Unix port, it's just an error, not on purpose.

**Comment by dacap** [comment]
Fixed with 19a11212edf80524972950240727a6c1d21fc1c5
